title: David Su 
#logo:
description: >
"<h3>About me</h3>As a recent graduate, I am looking to start my career in data analytics with a focus on roles that involve working with data, identifying insights, and supporting decision-making. I am enthusiastic about applying analytical thinking to solve real-world problems and contributing to projects that drive meaningful outcomes. My goal is to grow within a forward-thinking organisation where I can continue developing skills and add value through a detail-oriented and results-driven approach. <br><br> Email: yutongdavidsu@gmail.com <br> ðŸ‡¦ðŸ‡ºPhone: (+61) 0423 160 620 <br> ðŸ‡³ðŸ‡¿Phone: (+64) 0210 236 7193 <br> <br> "
  [<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" style="vertical-align:middle;">
  <path d="M12 .5C5.73.5.5 5.74.5 12.02c0 5.11 3.29 9.45 7.86 10.98.58.11.79-.25.79-.56
  0-.28-.01-1.02-.02-2-3.2.7-3.88-1.55-3.88-1.55-.53-1.36-1.29-1.72-1.29-1.72-1.05-.72.08-.71.08-.71
  1.16.08 1.77 1.2 1.77 1.2 1.03 1.77 2.7 1.26 3.36.96.1-.75.4-1.26.73-1.55
  -2.56-.29-5.26-1.28-5.26-5.71 0-1.26.45-2.29 1.19-3.1-.12-.29-.52-1.47.11-3.06
  0 0 .97-.31 3.18 1.18a11.02 11.02 0 0 1 5.8 0c2.21-1.49 3.18-1.18 3.18-1.18
  .63 1.59.23 2.77.11 3.06.74.81 1.19 1.84 1.19 3.1
  0 4.44-2.71 5.41-5.29 5.7.41.36.78 1.08.78 2.18
  0 1.58-.02 2.86-.02 3.25 0 .31.21.68.8.56
  4.56-1.53 7.85-5.87 7.85-10.98C23.5 5.74 18.27.5 12 .5z"/>
  </svg>](https://github.com/YOUR_GITHUB_USERNAME)
  &nbsp;
  [<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" style="vertical-align:middle;">
  <path d="M20.45 20.45h-3.55v-5.4c0-1.29-.02-2.95-1.8-2.95
  -1.8 0-2.08 1.4-2.08 2.85v5.5H9.47V9h3.4v1.56h.05
  c.47-.9 1.62-1.85 3.34-1.85 3.57 0 4.22 2.35 4.22 5.41v6.33z
  M5.34 7.43a2.06 2.06 0 1 1 0-4.12 2.06 2.06 0 0 1 0 4.12zM7.11 20.45H3.56V9h3.55v11.45z"/>
  </svg>](https://www.linkedin.com/in/YOUR_LINKEDIN_ID/)
show_downloads: false
theme: jekyll-theme-minimal #use this for now, view more at pages.github.com/themes/
