title: David Su 
#logo:
description: "As a recent graduate, I am looking to start my career in data analytics with a focus on roles that involve working with data, identifying insights, and supporting decision-making. I am enthusiastic about applying analytical thinking to solve real-world problems and contributing to projects that drive meaningful outcomes. My goal is to grow within a forward-thinking organisation where I can continue developing skills and add value through a detail-oriented and results-driven approach. <br> email: yutongdavidsu@gmail.com <br> phone: (+61) 0423 160 620"
show_downloads: false
theme: jekyll-theme-minimal #use this for now, view more at pages.github.com/themes/
